data:
  batch_size: 64
  characteristics:
    ch_0:
      max: 110.79493
      min: 1.4549588e-05
    ch_1:
      max: 80.487
      min: 5.4477514e-06
    ch_2:
      max: 125.859604
      min: 8.398932e-06
  img_size: 128
  img_stride: 16
  num_channels: 3
  num_workers: 4
  trainpath: ../datasets/SAN_FRANCISCO_ALOS2
  valid_ratio: 0.2
logging:
  logdir: ./logs
  wandb:
    project: gen_cvnn
loss:
  kld_weight: 1
  name: ComplexMSELoss
model:
  activation: modReLU
  channels_ratio: 32
  class: AutoEncoder
  latent_dim: 1024
  num_layers: 7
nepochs: 5000
optim:
  algo: Adam
  params:
    lr: 0.001
