data:
  batch_size: 8
  characteristics:
    ch_0:
      max: 110.79493
      min: 1.4549588e-05
    ch_1:
      max: 80.487
      min: 5.4477514e-06
    ch_2:
      max: 125.859604
      min: 8.398932e-06
  img_size: 128
  num_channels: 3
  num_workers: 4
  trainpath: ../datasets/SAN_FRANCISCO_ALOS2
  valid_ratio: 0.1
logging:
  logdir: ./logs
  wandb:
    project: gen_cvnn
loss:
  kld_weight: 0
  name: ComplexVAELoss
model:
  activation: modReLU
  channels_ratio: 64
  class: VAE
  latent_dim: 1024
  num_layers: 7
nepochs: 2000
optim:
  algo: Adam
  params:
    lr: 0.001
